version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "${VAULTAGE_DIR}:/var/www/vaultage:ro"
    links:
      - mysql:db
  nginx:
    image: nginx
    ports:
      - ${VAULTAGE_PORT}:80
    volumes:
      - "./nginx:/etc/nginx/conf.d:ro"
      - "${VAULTAGE_DIR}/public:/var/www/vaultage:ro"
    links:
      - php:php